### ISSUE TITLE
Trouble to jump

### ISSUE THREAD

**Issue by Andy7470** [robro/combomake#2]
Hello, nice app, but im trying to create a combo and combo requieres that character do a move, in this case im trying jump to right, in the game should be "9", but i can't get how to do it to the file. i know that character can jump with "jc" but does can't be a "9jc", the python script just don't get it.

**Comment by robro** [comment]
Check the timing.py file to see all the strings that are recognized. You either want to use "jcf" or "jcb" which stand for "jump cancel forward" and "jump cancel back" respectively. Characters are assumed to be facing to the right but you can use "ss" for "side switch" to swap that.

An important thing to keep in mind though is that I have not maintained this and several patches have been released since I stopped working on it, with many changes to every character, some of which affect the timings of their moves, so a lot of the timing data that I had to extract frame-by-frame is no longer accurate, which means you might get strange and unpredictable results.
